### ISSUE TITLE
Plugin writes changes to the file on disk?

### ISSUE THREAD

**Issue by sim590** [justmao945/vim-clang#29]
First time I do `<c-x><c-o>`, after one of the valid symbols (`::`,`.`,`->`), and then undo changes **I've done** using `u` in vim, I notice that the file has been wrote. In fact, I can do `:e!` and I see that the file on the disk has been wrote just after I've pressed `<c-x><c-o>`. Why does the plugin writes the file ? In my opinion, it shouldn't mess with writing my file on the disk if I don't want to.

**Comment by justmao945** [comment]
Yes, you are right, plugin will write file to disk before calling clang to parse this file. If you use :e!, that's the problem. Write to a tmp file before parsing may be another way to avoid this problem, but it may bring new problems...

**Comment by sim590** [comment]
Why not just let the user save his file and use the file that's already on disk ? What if the user didn't want to write the changes on disk while just trying to complete some words ? I'm asking questions hoping it helps the project.

**Comment by justmao945** [comment]
Hi @sim590 , relax, I'm really very happy to ask your questions and to fix issue to improve this project. I think you missed the point in my previous answer. The reason why I must save file is that, the completion engine clang **must read the latest file** to produce correct completions. If I only use the file that's already on disk, clang will never get the right completion point and source code, so it's impossible to produce the correct completion. That's why I give another solution to this problem, write to a tmp file before completion.

**Comment by sim590** [comment]
I'm sorry I didn't mean to create a misunderstanding; I'm convinced that you are opened to cricits and that we can discuss! I see your point. I think that using a *tmp* file would be more appropriate for the reasons I've said before. I'll put this feature into a TODO list and I'll make a pull request eventually. I can't promise for the meantime though since I'm having lots of work to do at University...

**Comment by justmao945** [comment]
Haha, that's great! Please feel relax to do this feature~

Some important points should be considered:
1. where to place the  tmp file
2. if the tmp file is not in the same dir with the source file, add current dir to include path
3. should replace the path and file name occurred in diagnostics window

**Comment by justmao945** [comment]
Hi @sim590 ,
I'd like to tell you, @mlen contribute a patch #43 to solve this problem just now. :smile:

**Comment by sim590** [comment]
Oh. That's great ! Thanks for telling !
